<?php

/**
 * @file
 * Contains drupalstat.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Theme hook
 */

function drupalstat_theme($existing, $type, $theme, $path) {

	$variables = array(
		'drupalstat' => array(
			'variables' => array(
				'drupalInfo' => null
			),
			'title' => 'Drupal Status',
			'template' => 'block--drupalstat',
		),
	);

	return $variables;

}

/**
 * Called after cache has been cleared so we can store the timestamp for reporting purposes in DrupalStat
 */

function drupalstat_rebuild() {
	// Store the current timestamp in a state variable
	\Drupal::state()->set('drupalstat.timestamp_cache_last_rebuild', time());
	\Drupal::state()->set('drupalstat.timestamp_cssjs_last_rebuild', time());
}

/**
 * Implements hook_install().
 */
function drupalstat_install() {
  $t = get_t();
  drupal_set_message($t("Congrats! DrupalStat settings are available under !link", 
    array( '!link' => l(t('admin/config/drupalstat'),  'admin/config/drupalstat'))
  ));
}

/**
 * Implements hook_menu().
 */
function drupalstat_menu() 
{
  $items['admin/config/system/drupalstat'] = array(
    'title' => 'DrupalStat Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupalstat_form'),
    'access arguments' => array('administer users'),
    'type' => MENU_NORMAL_ITEM,
  );
 
  return $items;
}

/**
 * Admin form to configure
 */
function drupalstat_form($form, &$form_state) 
{
  $form['drupalstat_configuration'] = array(
    '#type' => 'text',
    '#title' => t('CPU Load Average AJAX Refresh Rate (in seconds)'),
    '#required' => TRUE,
  	'#default_value' => variable_get('drupalstat_configuration', '60'),
  );
 
  return system_settings_form($form);
}

