<?php

/**
 * @file
 * Contains drupalstat.module
 */

/**
 * Theme hook
 */

function drupalstat_theme($existing, $type, $theme, $path) {

	$variables = array(
		'drupalstat' => array(
			'variables' => array(
				'drupalInfo' => null
			),
			'title' => 'Drupal Status',
			'template' => 'block--drupalstat',
		),
	);

	return $variables;

}

/**
 * Called after cache has been cleared so we can store the timestamp for reporting purposes in DrupalStat
 */

function drupalstat_rebuild() {
	// Store the current timestamp in a state variable
	\Drupal::state()->set('drupalstat.timestamp_cache_last_rebuild', time());
	\Drupal::state()->set('drupalstat.timestamp_cssjs_last_rebuild', time());
}
